

name: Deploy to Amazon ECS

on:
  push:
    branches:
      - maven

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn -X

   
