name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
     - name: Huawei CLoud Software Repository for Container (SWR) Login
       uses: huaweicloud/swr-login@v1
       with:
         region: 'cn-north-4' # example: ap-southeast-3
         access-key-id: ${{ secrets.ACCESSKEY }}
         access-key-secret: ${{ secrets.SECRETACCESSKEY }}
     - run: |
        echo $DOCKER_CONFIG
